<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT_TS003_CSV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e3d5d4e7-20e8-4579-9a10-06e5c40b2eff</testSuiteGuid>
   <testCaseLink>
      <guid>5bb37c6e-3e25-46ea-8180-24bad90c79d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC DDT/TC002_Login into application excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6d97c5ae-ce44-49dc-8bfe-0fba045973f6</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-3</value>
         </iterationEntity>
         <testDataId>Data Files/DF003</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6d97c5ae-ce44-49dc-8bfe-0fba045973f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>88dcc304-555e-4aea-aa3a-c78ec62f00ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6d97c5ae-ce44-49dc-8bfe-0fba045973f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f02fc46d-b14c-4c5e-8397-da16f50097bf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
