<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT_TS002_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3cbff082-5edd-4046-b8a2-530fbc5033b8</testSuiteGuid>
   <testCaseLink>
      <guid>5bb37c6e-3e25-46ea-8180-24bad90c79d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC DDT/TC002_Login into application excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f75b0af0-a03c-4c43-8f30-6eb6938b72cb</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/DF002</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f75b0af0-a03c-4c43-8f30-6eb6938b72cb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>88dcc304-555e-4aea-aa3a-c78ec62f00ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f75b0af0-a03c-4c43-8f30-6eb6938b72cb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f02fc46d-b14c-4c5e-8397-da16f50097bf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
